apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
    tier: back
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  strategy: {}
  template:
    metadata:
      labels:
        app: worker
        tier: back
    spec:
      containers:
      - image: schoolofdevops/worker:latest
        name: worker
